import './globals.css'
import { Roboto } from 'next/font/google'
import Nav from "./Components/Navbar/page";
import  Layout from "./Components/Layout/page";

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Layout>
        <Nav/> 
        {children}
        </Layout>
        </body>
    </html>
  )
}
